# 项目相关配置
ruoyi:
  # 名称
  name: RuoYi
  # 版本
  version: 3.2.1
  # 版权年份
  copyrightYear: 2020
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: E:/ruoyi/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
#  port: 8090 服务器上
#  port: 8089 本地
  port: 8090
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn

# Spring配置
spring:
  jmx:
    default-domain: rec
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles: 
    active: druid
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  10MB
       # 设置总上传的文件大小
       max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
#  # redis 配置
#  redis:
#    # 地址
#    host: www.chuangkeinfo.com
#    # 端口，默认为6379
#    port: 6379
#    # 密码
#    password: innovation118
#    # 连接超时时间
#    timeout: 10s
#    lettuce:
#      pool:
#        # 连接池中的最小空闲连接
#        min-idle: 0
#        # 连接池中的最大空闲连接
#        max-idle: 8
#        # 连接池的最大数据库连接数
#        max-active: 8
#        # #连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1ms

# token配置
token:
    # 令牌自定义标识
    header: Authorization
    # 令牌密钥
    secret: abcdefghijklmnopqrstuvwxyz
    # 令牌有效期（默认30分钟）
    expireTime: 30
  
# MyBatis配置
#mybatis:
#    # 搜索指定包别名
#    typeAliasesPackage: com.ruoyi.**.domain
#    # 配置mapper的扫描，找到所有的mapper.xml映射文件
#    mapperLocations: classpath*:mapper/**/*Mapper.xml
#    # 加载全局的配置文件
#    configLocation: classpath:mybatis/mybatis-config.xml
    
# Mybatis-plus配置  
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.ruoyi.**.domain
  global-config:
    banner: true
    db-config:
      field-strategy: ignored
      column-underline: false
      capital-mode: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

# PageHelper分页插件
pagehelper: 
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql 

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

# 防止XSS攻击
xss: 
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

#临时网关服务器配置
#视频网关服务器IP
LocalIP: 192.168.10.172
#视频网关服务器Port
LocalPort: 5068
#软交换IP
ServerIP: 192.168.10.172
#软交换Port
ServerPort: 5060
#软交换给网关服务器分配的账号
USERNAME: 6007
#软交换给网关服务器分配的账号的密码
PASSWD: 123456
#监控信息存储的xml地止
GB_PATH: ..//config//camera.xml
#其他程序调用网关服务器的端口
HTTP: 7777
#GB28181服务器注册到视频网关服务器的端口
GB28181PORT: 15070
#GB28181服务器(多个时可共用)注册到视频网关服务器的id
GB28181CODE: 34000000002000000010
#视频网关服务器通知消息指向的地止
HTTPURL: http://192.168.10.211:8090/gbNotice
#直播分享默认有效时长（秒）
CLOSE_WAIT_TIME: 30

#监控存储路径camera.xml
monitor_camera_url: /home/ck/data/config/camera.xml

#网页引用地址
sharePage: 127.0.0.1:3001/#/videoCloud

#lincense服务器存储地址
license_address: /home/ck/data/config
file:
  base-url: